version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    container_name: "db"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: "pgadmin4"
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: emasa@emasa.com
      PGADMIN_DEFAULT_PASSWORD: admin

  api:
    image: server_emasa
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
volumes:
  db_data:
